apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  mongodb-username: dXNlcm5hbWU=
  mongodb-password: cGFzc3dvcmQ=
  mongo-express-username: dXNlcm5hbWU=
  mongo-express-password: cGFzc3dvcmQ=
